### ISSUE TITLE
Its not finding the path ... see in settings.py my tortoise-conf is present but it saying module not found

### ISSUE THREAD

**Issue by sakthiRathinam** [tortoise/tortoise-cli#1]
Error: Error while importing configuration module: No module named 'settings'
root@4288e7c9f646:/app# tortoise-cli -c settings.TORTOISE_ORM shell
Error: Error while importing configuration module: No module named 'settings'
root@4288e7c9f646:/app# ls
DockerProdFile	__init__.py  aerich.ini    docker-compose.yaml	main.py     pip		      settings.py  static
Dockerfile	__pycache__  commands.txt  env			migrations  requirements.txt  src	   tortoise-cli

**Comment by long2ice** [comment]
You can reference examples, maybe settings should in a python package which contains `__init__.py`

**Comment by sakthiRathinam** [comment]
i have added __init__.py in all the folders but its not finding the path 
https://github.com/sakthiRathinam/fastapicore
do u please check this project link mention above the tortoise_orm is present in src/config/tortoise_conf
root@4288e7c9f646:/app# tortoise-cli -c src.config.tortoise_conf.TORTOISE_ORM shell
Error: Error while importing configuration module: No module named 'src

**Comment by long2ice** [comment]
I update, you can try latest source code, if right I will release a new version

**Comment by sakthiRathinam** [comment]
its working fine now.....update the version
